---
- name: Get Kubernetes join command from controller
  become: true
  shell: kubeadm token create --print-join-command
  register: join_command
  delegate_to: kubernetes_control_plane

- name: Join Kubernetes cluster
  become: true
  command: "{{ join-command.stdout }}"