---
- name: Setup Kubernetes controllers
  hosts: kubernetes_control_plane
  vars_files:
    - inventory/group_vars/all.yaml
  roles:
    - k8s-controller

- name: Setup Kubernetes workers
  hosts: kubernetes_worker
  vars_files:
    - inventory/group_vars/all.yaml
  roles:
    - k8s-worker