services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /srv/portainer:/data
    ports:
      - 9000:9000
    security_opt:
      - no-new-privileges:true

  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
    volumes:
      - /srv/uptime-kuma:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 3001:3001
