apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb
resources:
  - strict_arp.yaml
  - namespace.yaml
  - github.com/metallb/metallb/config/native?ref=v0.13.9
  - addresses.yaml