all:
  children:
    kubernetes:
      children:
        kubernetes_control_plane:
          hosts:
            k8s-controller:
              ansible_host: 10.10.100.200
        kubernetes_worker:
          hosts:
            k8s-worker01:
              ansible_host: 10.10.100.201