services:

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Detroit
    volumes:
      - /srv/pihole:/etc/pihole
    ports:
      - "53:53"
      - "7654:80"