---
- name: Install containerd
  become: true
  ansible.builtin.package:
    name: containerd
    state: latest
    update_cache: true

- name: Configure containerd
  become: true
  block:
    - name: Create containerd directories required
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /etc/containerd

    - name: Check containerd config file populated
      ansible.builtin.stat:
        path: /etc/containerd/config.toml
      register: containerd_config

    - name: Write containerd default config file
      ansible.builtin.shell: containerd config default > /etc/containerd/config.toml
      when: not containerd_config.stat.exists

    - name: Edit containerd config.toml file
      replace:
        path: /etc/containerd/config.toml
        regexp: '^(\s*)SystemdCgroup\s*=\s*false(\s*)$'
        replace: '\1SystemdCgroup = true\2'
      register: config_update

    - name: Enable containerd service
      ansible.builtin.service:
        name: containerd
        state: restarted
        enabled: true
        daemon_reload: true
      when: config_update.changed