---
- name: Include kubeadm init task
  import_tasks: initialize_kubernetes.yaml

- name: Include kubeconfig setup task
  import_tasks: setup_kube_config.yaml

- name: Include Flannel installation task
  import_tasks: install_flannel.yaml