---
- name: Disable swap
  become: true
  ansible.builtin.shell: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swap from fstab
  become: true
  ansible.builtin.replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+.*)$'
    replace: '# \1'