---
#- name: Check that hardware requirements are met

#- name: Ensure unique MAC address and product_uuid

- name: Install some packages needed to configure the nodes
  become: true
  ansible.builtin.package:
    name:
      - ca-certificates
      - curl
      - gnupg2
      - lsb-release
    state: latest