services:
  homer:
    image: b4bz/homer
    container_name: homer
    restart: unless-stopped
    environment:
      - INIT_ASSETS=1 # default
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
    volumes:
      - /srv/homer:/www/assets
    ports:
      - 8902:8080
    user: 1000:1004 # default

  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - NVIDIA_VISIBLE_DEVICES=all
    group_add:
      - "107"
      - "44"
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/media:/data/media
    ports:
      - 8920:8920
      - 8096:8096
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  komga:
    image: gotson/komga
    container_name: komga
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - JAVA_TOOL_OPTIONS=-Xmx1g
    volumes:
      - type: bind
        source: /srv/komga/config
        target: /config
      - type: bind
        source: /srv/media/manga
        target: /data
      - type: bind
        source: /etc/timezone
        target: /etc/timezone
    ports:
      - 8080:8080

  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=nord
    volumes:
      - /srv/sonarr/config:/config
      - /srv/downloads:/downloads
      - /srv/media:/media
    ports:
      - 8989:8989

  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=nord
    volumes:
      - /srv/radarr/config:/config
      - /srv/downloads:/downloads
      - /srv/media:/media
    ports:
      - 7878:7878

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=nord
    volumes:
      - /srv/lidarr/config:/config
      - /srv/downloads:/downloads
      - /srv/media:/media
    ports:
      - 8686:8686

  mylar:
    image: lscr.io/linuxserver/mylar3
    container_name: mylar
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:mylar3
      - TP_THEME=nord
    volumes:
      - /srv/mylar/config:/config
      - /srv/downloads:/downloads
      - /srv/media/manga:/manga
    ports:
      - 8090:8090

  transmission-openvpn:
    image: haugene/transmission-openvpn
    container_name: transmission-openvpn
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      - OPENVPN_PROVIDER=surfshark
      - OPENVPN_CONFIG=us-dtw.prod.surfshark.com_udp
      - OPENVPN_USERNAME=$OPENVPN_USERNAME
      - OPENVPN_PASSWORD=$OPENVPN_PASSWORD
      - LOCAL_NETWORK=192.168.88.0/24
    volumes:
      - '/srv/downloads/:/data'
      - '/srv/transmission-openvpn/config/:/config'
    ports:
      - '9091:9091'
    logging:
      driver: json-file
      options:
        max-size: 10m

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:jackett
      - TP_THEME=nord
    volumes:
      - /srv/jackett/config:/config
    ports:
      - 9117:9117

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    restart: unless-stopped
    environment:
      - LOG_LEVEL=debug
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
      - BASE_PATH=/jellyseerr
    ports:
      - 5055:5055
    volumes:
      - /srv/jellyseerr/config:/app/config

  requestrr:
    image: lscr.io/linuxserver/requestrr:latest
    container_name: requestrr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1004
      - TZ=America/Detroit
    volumes:
      - /srv/requestrr/config:/config
    ports:
      - 4545:4545
