---
- name: Add Kubernetes 
  become: true
  block:
    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/trusted.gpg.d/docker.asc
        mode: '0644'
        force: true

    - name: Add Docker apt repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker

- name: Install containerd
  become: true
  ansible.builtin.package:
    name: containerd.io
    state: latest
    update_cache: true

- name: Enable docker service
  become: true
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true